runtime: python27
threadsafe: true

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /.*
  script: twitchrss.app

automatic_scaling:
  max_instances: 1
  max_idle_instances: 1

